/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { ImmirisNotary } from "./ImmirisNotary";

export { ImmirisNotary__factory } from "./factories/ImmirisNotary__factory";
